max_steps = 200
batch_size = 512
seq_len = 4096
rollouts_per_example = 16
mask_truncated_completions = false
seed = 2001

[model]
name = "Qwen/Qwen2.5-0.5B-Instruct"

[wandb]
platform = "tensorboard"
project = "AS_to_100"
name = "orch_dppo_lr=2e6_temp=1_topP=1_topK=8_r4"

[[env]]
id = "alphabet-sort"
args = { min_turns = 2, max_turns = 2, seed=2001 }

[sampling]
max_tokens = 128
temperature = 1.0
seed = 2001

[buffer]
seed = 2001

[wandb.log_extras]
interval = 50

[eval]
interval = 10
rollouts_per_example = 4
num_examples = 128

[[eval.env]]
id = "alphabet-sort"
args = {"min_turns" = 2, "max_turns"= 2, "seed"= 2001}

[eval.sampling]
max_tokens = 128
temperature = 0.7
top_p = 1.0
top_k = -1
seed = 2001