max_steps = 150

[model]
name = "Qwen/Qwen2.5-0.5B-Instruct"

[optim]
lr = 3e-6

[wandb]
platform = "tensorboard"
project = "AS_to_100"
name = "train_which_topk_and_support?"

[loss]
type = "dppo"
ratio_type = "token"
dppo_delta = 0.2

[ckpt]
interval = 5

[ckpt.weights]
save_sharded = true
save_format = "safetensors"

