max_steps = 5
batch_size = 512
seq_len = 8192
rollouts_per_example = 8
mask_truncated_completions = false

[model]
name = "Qwen/Qwen2.5-1.5B"

[wandb]
platform = "tensorboard"
project = "slimpeft"
name = "orch_qwen1.5B-base-gsm8k-4-weight_norm_random10_demoo_1111"

[[env]]
id = "hendrycks-math"

[sampling]
max_tokens = 2048

[wandb.log_extras]
interval = 10


