max_steps = 5

[model]
name = "Qwen/Qwen2.5-1.5B"

[tokenizer]
chat_template = """
{%- if messages[0]['role'] == 'system' %}
    {{- '<|im_start|>system\n' + messages[0]['content'] + '<|im_end|>\n' }}
{%- else %}
    {{- '<|im_start|>system\nYou are a helpful mathematical AI assistant. Please reason step by step, and put your final answer within \\\\boxed{}.<|im_end|>\n' }}
{%- endif %}
{%- for message in messages %}
    {%- if message['role'] == 'user' or (message['role'] == 'system' and not loop.first) %}
        {{- '<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n' }}
    {%- elif message['role'] == 'assistant' %}
        {{- '<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n' }}
    {%- endif %}
{%- endfor %}
{%- if add_generation_prompt %}
    {{- '<|im_start|>assistant\n' }}
{%- endif %}
"""


[optim]
type = "sparse_adamw"
lr = 1e-5

[wandb]
platform = "tensorboard"
project = "slimpeft"
name = "train_qwen1.5B-base-gsm8k-4-weight_norm_random10_demoo_1111"


