max_steps = 600
batch_size = 128 # full size is 1024
micro_batch_size = 1
seq_len = 2048
rollouts_per_example = 16
mask_truncated_completions = false

[model]
name = "Qwen/Qwen2.5-0.5B-Instruct"

[monitor.wandb]
project = "alphabet-sort"
space_id = "alphabet-sort"
dataset_id = "alphabet-sort"
name = "max_tokens=512,max_turns=3,max_steps=600_round_3"

[monitor.wandb.log_extras]
samples = true
distributions = true
interval = 2

[environment]
id = "alphabet-sort"

[environment.args]
min_turns = 2
max_turns = 3

[sampling]
max_tokens = 512

[ckpt]
interval = 100