max_steps = 200

[monitor.wandb]
project = "alphabet-sort"
space_id = "alphabet-sort"
dataset_id = "alphabet-sort"
name = "512_sampling_len"

[model]
name = "Qwen/Qwen2.5-0.5B-Instruct"

[optim]
lr = 1e-6